export const ADD_LAWYERS='ADD_LAWYERS';
export const LAWYERS_LOADING='LAWYERS_LOADING';
export const LAWYERS_FAILED='LAWYERS_FAILED';

export const ISLAWYERLOGGEDIN='ISLAWYERLOGGEDIN';
export const ISUSERLOGGEDIN='ISUSERLOGGEDIN';
export const USERLOGGEDOUT='USERLOGGEDOUT';

export const ADD_PROFILEDATA='ADD_PROFILEDATA';
export const ADD_PROFILEDATA_LOADING='ADD_PROFILEDATA_LOADING';
export const ADD_PROFILEDATAFAILED='ADD_PROFILEDATAFAILED';

export const ADD_USERCASES='ADD_USERCASES';
export const ADD_TO_USERCASES='ADD_TO_USERCASES';
export const ADD_USERCASES_LOADING='ADD_USERCASES_LOADING';
export const ADD_USERCASESFAILED='ADD_USERCASESFAILED';
export const ACCEPT_BY_USER='ACCEPT_BY_USER';


export const ADD_ALLCASES='ADD_ALLCASES';
export const ADD_ALLCASES_LOADING='ADD_ALLCASES_LOADING';
export const ADD_ALLCASESFAILED='ADD_ALLCASESFAILED';
export const FILTER_ALLCASES='FILTER_ALLCASES';

export const ERROR_MESSAGE='ERROR_MESSAGE';
export const SUCCESS_MESSAGE='SUCCESS_MESSAGE';
export const CLEAR_MESSAGE='CLEAR_MESSAGE';

export const LOADING='LOADING';
export const CLEAR_LOADING='CLEAR_LOADING';

export const ADD_DETAILPAGE='ADD_DETAILPAGE';
export const ADD_DETAILPAGE_LOADING='ADD_DETAILPAGE_LOADING';
export const ADD_DETAILPAGEFAILED='ADD_DETAILPAGEFAILED';