export const ADD_LAWYERS='ADD_LAWYERS';
export const LAWYERS_LOADING='LAWYERS_LOADING';
export const LAWYERS_FAILED='LAWYERS_FAILED';

export const ISLAWYERLOGGEDIN='ISLAWYERLOGGEDIN';
export const ISUSERLOGGEDIN='ISUSERLOGGEDIN';
export const USERLOGGEDOUT='USERLOGGEDOUT';

export const ADD_PROFILEDATA='ADD_LAWYERPROFILEDATA';
export const ADD_PROFILEDATA_LOADING='ADD_LAWYERPROFILEDATA_LOADING';
export const ADD_PROFILEDATAFAILED='ADD_LAWYERPROFILEDATAFAILED';

export const ADD_USERCASES='ADD_USERCASES';
export const ADD_USERCASES_LOADING='ADD_USERCASES_LOADING';
export const ADD_USERCASESFAILED='ADD_USERCASESFAILED';

export const ADD_ALLCASES='ADD_ALLCASES';
export const ADD_ALLCASES_LOADING='ADD_ALLCASES_LOADING';
export const ADD_ALLCASESFAILED='ADD_ALLCASESFAILED';